# Generated by Django 3.2.5 on 2021-12-18 22:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipe_name', models.CharField(max_length=255)),
                ('ingredients', models.TextField()),
                ('preparation_method', models.TextField()),
                ('preparation_time', models.IntegerField()),
                ('yields_volume', models.IntegerField()),
                ('category', models.CharField(max_length=100)),
                ('insert_date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
        ),
    ]
