# Generated by Django 3.2.5 on 2021-12-19 01:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pessoas', '0001_initial'),
        ('receitas', '0002_alter_recipe_yields_volume'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='person_id',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='pessoas.person'),
            preserve_default=False,
        ),
    ]
